export type TFilter =
    |"Others"
    |"General knowledge"
    |"Sports"
    |"Anime"
    |"Movie"
    |"Series" 
    |"Music"
    |"Game"
    |"Funny"
    |"Fashion/Style"
    |"Curiosity"
    |"Life/Relationships"
    |"Decoration"
    |"Health"
    |"Beauty"
    |"Literature"
    |"Pop Culture"
    |"Art"
    |"Trips"
    |"Nature"
    |"Career"
    |"Gastronomy"
    |"Animals"
    |"Hobbies"
    |"Mythology"
    |"Psychology"
    |"Languages"
    |"Education"
    |"Book"
    |"Nerd Culture"
    |"Business and Economy"

export type TFilterPt =
    | "Outros"
    | "Conhecimentos gerais"
    | "Esportes"
    | "Anime"
    | "Filme"
    | "Séries"
    | "Música"
    | "Jogo"
    | "Humor"
    | "Moda/Estilo"
    | "Curiosidade"
    | "Vida/Relacionamentos"
    | "Decoração"
    | "Saúde"
    | "Beleza"
    | "Literatura"
    | "Cultura Pop"
    | "Arte"
    | "Viagens"
    | "Natureza"
    | "Carreira"
    | "Gastronomia"
    | "Animais"
    | "Hobbies"
    | "Mitologia"
    | "Psicologia"
    | "Idiomas"
    | "Educação"
    | "Livro"
    | "Cultura Nerd"
    | "Negócios e Economia";


export type TFilterEs =
    | "Otros"
    | "Conocimientos generales"
    | "Deportes"
    | "Anime"
    | "Película"
    | "Series"
    | "Música"
    | "Juego"
    | "Humor"
    | "Moda/Estilo"
    | "Curiosidad"
    | "Vida/Relaciones"
    | "Decoración"
    | "Salud"
    | "Belleza"
    | "Literatura"
    | "Cultura Pop"
    | "Arte"
    | "Viajes"
    | "Naturaleza"
    | "Carrera"
    | "Gastronomía"
    | "Animales"
    | "Hobbies"
    | "Mitología"
    | "Psicología"
    | "Idiomas"
    | "Educación"
    | "Libro"
    | "Cultura Nerd"
    | "Negocios y Economía";