export type TFilter =
    |"Others"
    |"General knowledge"
    |"Sports"
    |"Anime"
    |"Movie"
    |"Series" 
    |"Music"
    |"Game"
    |"Funny"
    |"Fashion/Style"
    |"Curiosity"
    |"Life/Relationships"
    |"Decoration"
    |"Health"
    |"Beauty"
    |"Literature"
    |"Pop Culture"
    |"Art"
    |"Trips"
    |"Nature"
    |"Career"
    |"Gastronomy"
    |"Animals"
    |"Hobbies"
    |"Mythology"
    |"Psychology"
    |"Languages"
    |"Education"
    |"Book"
    |"Nerd Culture"
    |"Business and Economy"