import "./globals.scss";
import type { Metadata } from "next";
import { ProviderTheme} from "@/contexts/themeContext";
import { GlobalMessageProvider } from "@/contexts/globalMessageContext";
import { FilterProvider } from "@/contexts/filtersContext";


export const metadata: Metadata = {
    description: "Generated by create next app"
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
                <body>
                    <ProviderTheme attribute="data-theme" defaultTheme="system" enableSystem>
                        <GlobalMessageProvider>
                            <FilterProvider>
                                {children}
                            </FilterProvider>
                        </GlobalMessageProvider>
                    </ProviderTheme>
                </body>
        </html>
    );
}
