import "../globals.scss";
import type { Metadata } from "next";
import { ProviderTheme} from "@/contexts/themeContext";
import { GlobalMessageProvider } from "@/contexts/globalMessageContext";
import { FilterProvider } from "@/contexts/filtersContext";
import GlobalMessageWidget from "@/components/HandlerMessage/global-message-widget";
import { UserProvider } from "@/contexts/userContext";
import { ReactNode } from "react";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
    description: "Generated by create next app"
};

export default async function RootLayout({
    children,
    params
}: {
    children: ReactNode;
    params: Promise<{locale: string}>;
}) {
    const {locale} = await params;
    const messages = await getMessages({locale})
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }
    return (
        <html lang={locale} suppressHydrationWarning>
            <body>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <GlobalMessageProvider>
                        <UserProvider>
                            <ProviderTheme attribute="data-theme" defaultTheme="system" enableSystem>
                                <FilterProvider>
                                    <GlobalMessageWidget />
                                    {children}
                                </FilterProvider>
                            </ProviderTheme>
                        </UserProvider>
                    </GlobalMessageProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
